### ISSUE TITLE
The sample application is not working for iOS.

### ISSUE THREAD

**Issue by ngalicoco** [chaosifier/TabView#1]
It works great for Android and UWP, for iOS though the tabs are displayed, but the content is not.

**Comment by alejandroschmechel** [comment]
yeah, same thing here

**Comment by TheRealNyquist** [comment]
I had the same problem. Since TabView relies on CarouselView you need to call `CarouselViewRenderer.Init();`
In your iOS AppDelegate.cs. After that it worked perfectly.

**Comment by chaosifier** [comment]
Thank you @TheRealNyquist. I had mentioned in readme that it relies on CarouselView. I think I should also have mentioned that CarouselView needs to be initialized first for TabView to work properly.
