### ISSUE TITLE
Tabs behavior doesn't work on Android but works fine on iOS

### ISSUE THREAD

**Issue by Aerevia** [chaosifier/TabView#16]
Hello,
I have a problem using your library, it works well on iOS and is awesome ! 
But on android sliding and tab changing doesn't work well. For exemple i'm setting up 4 tabs, and switching between them is buggy

Tab 1 (contains "test") :
![image](https://user-images.githubusercontent.com/13220181/44519201-a49b9900-a6cc-11e8-9271-6c5116993a20.png)

Tab 2 (contains "test2") :
![image](https://user-images.githubusercontent.com/13220181/44519210-acf3d400-a6cc-11e8-8867-4f989f693594.png)

Tabs 3 and 4 never show anything on android and sometimes Tab 2 show the content of Tab 1 like this :
![image](https://user-images.githubusercontent.com/13220181/44519377-1ecc1d80-a6cd-11e8-9237-146fb689d7ec.png)

Moreover sliding is also fine on iOS but not on android.

CarouselViewRenderer is initialized on both projects.

What could be causing this ?

**Comment by AndreiMisiukevich** [comment]
@Aerevia try it with https://github.com/AndreiMisiukevich/CardView

**Comment by chaosifier** [comment]
The slow tab switching issue has been fixed.
