### ISSUE TITLE
[IOS] Crash : NSInternalInconsistencyException Reason: No view controller managing visible view

### ISSUE THREAD

**Issue by pumpkintechlabs** [chaosifier/TabView#17]
Happens only when tabs have long text that wraps around on a tab. and you click on tabs to navigate between them.

`
var tabs = new List<TabItem>(){

                new TabItem("Tab with a very long text 1", new Label{Text = "Tab 1", HorizontalOptions = LayoutOptions.FillAndExpand, VerticalOptions = LayoutOptions.FillAndExpand, BackgroundColor = Color.Red}),
                new TabItem("Tab with a very long text 2", new Label{Text = "Tab 2", HorizontalOptions = LayoutOptions.FillAndExpand, VerticalOptions = LayoutOptions.FillAndExpand, BackgroundColor = Color.Green}),
                new TabItem("Tab with a very long text 3", new Label{Text = "Tab 3", HorizontalOptions = LayoutOptions.FillAndExpand, VerticalOptions = LayoutOptions.FillAndExpand, BackgroundColor = Color.Blue}),
            }; 
`

**Comment by CleverSoftwarePoland** [comment]
I have the same problem. Did you find any solution to that problem?

**Comment by pantelisGeo90** [comment]
I can also confirm of this issue. 
Case scenario:
If one of your tap-titles are longer that the others (i.e. the text breaks to the next line) and the user taps to navigate to the according tab, the app crashes.

![ios-crash](https://user-images.githubusercontent.com/6824561/65281870-71c01080-db2b-11e9-8577-02f5724b9ad9.gif)

**Comment by NaiShengYu** [comment]
I have the same problem.when tabs have long text

**Comment by felipechavez** [comment]
I have the same problem. Did you find any solution to that problem?

**Comment by chaosifier** [comment]
With the new version, the tab header will be scrollable when the content width exceeds available width. This should fix the issue.
