### ISSUE TITLE
Tab Separator

### ISSUE THREAD

**Issue by AbhijeetChowdhury** [chaosifier/TabView#21]
Hi @chaosifier ,

Could it be possible to add a separator in the Tab Header between two tabs and change the Color of the separator as well?

Please find the attached screenshot for the reference.

![image](https://user-images.githubusercontent.com/32019318/54336504-3f9c9600-4652-11e9-96b1-a2038e37ca55.png)

**Comment by chaosifier** [comment]
You could achieve this with TabHeaderItemTemplate property in the new version. Please refer to sample and readme for guidance.
