### ISSUE TITLE
Delay when sliding through pages

### ISSUE THREAD

**Issue by agharium** [chaosifier/TabView#27]
Hi all!

I got the exact same problem as #3, but I can't apply the fix given by #3's op, because I'm not using the same element (not in a 'direct' way at least). I believe that this plugin has received some kind of update since #3's op found out the fix.

While #3's fix was based on manipulating the `OnPropertyChanged` event and changing a couple of attributes of a `CarouselView`, I'm using a `TabView` (according to samples given by the author) to display my tabs, and it doesn't have the same attributes as a `CarouselView` (`Position`, for instance).

Can someone help me?

**Comment by agharium** [comment]
The problem is a sort of delay on the tab indicator when sliding through the tabs. Here's an example: [check it out](https://drive.google.com/open?id=1z4nRvvoWtml07MNGLDqwx7I3VPOXbOGM). 

Can someone please help me?

**Comment by chaosifier** [comment]
I've fixed the issue. Will shortly update the nuget package.

**Comment by agharium** [comment]
waiting on the nuget
Thanks
