### ISSUE TITLE
Slidable option for the tabview header instead of break-line on the text (if there are a lot)

### ISSUE THREAD

**Issue by pantelisGeo90** [chaosifier/TabView#28]
Hello,
This is a greak nuget package 👍 

I was wondering if there is an option to make the tab view header slidable if there a lot of items within, instead of trying to fit everything in the screen and break line on the text inside the tabs? In 

I've had a quick look in the other issues but i don't think they mention anything like this (maybe i missed it if the do mention it)

Thank you in advance.

**Comment by chaosifier** [comment]
Thank you for the feedback. The feature has been added.
