### ISSUE TITLE
Delay sliding through pages

### ISSUE THREAD

**Issue by masiri201** [chaosifier/TabView#3]
There is a considerable delay when sliding through the pages on the tab view, when i click the tabs it's no problem, but when i slide the pages the tab takes a while to reload and select the proper one. If somebody knows the solution for this please help me.

**Comment by chaosifier** [comment]
I haven't faced such an issue yet. What are the contents of your tab items? It would be easier if you could share some code.

**Comment by masiri201** [comment]
Hello, My tab Items are just content pages with a label on the middle for now.

The delay its not in the slide, the slide responds well and fast, it's the tab indicator that takes a while to change the tab.

List<TabItem> tabs = new List<TabItem>();
            TabItem tabMaquinas = new TabItem("Máquinas", maquinas.Content); 
            TabItem tabStock = new TabItem("Stock",stock.Content);
            TabItem tabNoticias = new TabItem("Notícias",noticias.Content);
            tabs.Add(tabMaquinas);
            tabs.Add(tabStock);
            tabs.Add(tabNoticias);
            TabViewControl tabView = new TabViewControl(tabs, 0) {
                HeaderBackgroundColor = Color.Transparent,
                HeaderSelectionUnderlineColor = (Color)Application.Current.Resources["CustomOrange"],
                HeaderSelectionUnderlineWidth = 50,
                HeaderTabTextColor = (Color)Application.Current.Resources["CustomGrayPressed"],
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
            };

**Comment by chaosifier** [comment]
I tried by setting different views includeing images and stack layouts, but couln't recreate the problem. What are the contents of your TabItems?

**Comment by masiri201** [comment]
Yes that's exactly what i'm talking about @zaoky  thanks for clarifying ;)

**Comment by masiri201** [comment]
I've managed to fix this by adding 

` SetPosition(positionChangingArgs.NewPosition);`

to the carousel view PropertyChanged Event so it looks like this:

`private bool _supressCarouselViewPositionChangedEvent = false;
        private void _carouselView_PropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(_carouselView.Position) && !_supressCarouselViewPositionChangedEvent)
            {
                var positionChangingArgs = new PositionChangingEventArgs()
                {
                    Canceled = false,
                    NewPosition = _carouselView.Position,
                    OldPosition = _position
                };

                OnPositionChanging(ref positionChangingArgs);

                if (positionChangingArgs != null && positionChangingArgs.Canceled)
                {
                    _supressCarouselViewPositionChangedEvent = true;
                    _carouselView.PositionSelected -= _carouselView_PositionSelected;
                    _carouselView.PropertyChanged -= _carouselView_PropertyChanged;
                    _carouselView.Position = _position;
                    _carouselView.PositionSelected += _carouselView_PositionSelected;
                    _carouselView.PropertyChanged += _carouselView_PropertyChanged;
                    _supressCarouselViewPositionChangedEvent = false;
                }

                SetPosition(positionChangingArgs.NewPosition);
            }
        }`

**Comment by zaoky** [comment]
Great @masiri201 you did it.

Many thanks for sharing your solution, it works great 🥇 !
