### ISSUE TITLE
Assembly information lost in recent update

### ISSUE THREAD

**Issue by jsuvanto** [chaosifier/TabView#32]
It appears that the file `Xam.Plugin.TabView/Xam.Plugin.TabView.csproj` has broken in commit 1c5c2d4f2be8f50022d270a23ff728be6832f746.

Xam.Plugin.TabView version 1.0.5, installed from NuGet package.

Effectively, the control cannot be used in XAML anymore. I'm adding the control inside a ContentPage element like this:

```xml
<ContentPage xmlns:tabview="clr-namespace:Xam.Plugin.TabView;assembly=Xam.Plugin.TabView">
```

This creates the following error messages in VS2019:

```
Assembly 'Xam.Plugin.TabView' was not found. Verify that you are not missing an assembly reference. Also, verify that your project and all referenced assemblies have been built.
The type 'tabview:TabViewControl' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
Failed to resolve assembly: 'Xam.Plugin.TabView, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```

I believe this is caused by the aforementioned file being almost a copy of the `.nuspec` file. According to the commit diff, the old .csproj file has been moved to a directory called `TabView - Copy` but that does not seem to be included in the repository.

Meanwhile I'm reverting to an older version. 1.0.4 seems to work.

**Comment by chaosifier** [comment]
I couldn't recreate the issue. Moreover, the sample application in this repo has both code behind and xaml versions of the TabView used, they seem to work fine. Could you please delete the bin and obj directories and try again after restarting vs to be sure that it isn't some other issue?

**Comment by hhuseyinpay** [comment]
I just upgraded tab 1.0.4 to 1.0.5  and the following error messages raised

```
DailyStudyPage.xaml.cs(7, 7): [CS0246] DailyStudy/DailyStudyPage.xaml.cs(7,7): error CS0246: The type or namespace name 'Xam' could not be found (are you missing a using directive or an assembly 
DailyStudyPage.xaml.g.cs(23, 25): [CS0400] obj/Debug/netstandard2.0/DailyStudy/DailyStudyPage.xaml.g.cs(23,25): error CS0400: The type or namespace name 'Xam' could not be found in the global namespace (are you missing an assembly reference?)
```

I tried to clean the solution and delete the bin and obj directories but didn't work for me.

**Comment by chaosifier** [comment]
Does building only the shared project succeed?
And could you also share the version of xamarin.forms that you're using. Also make sure that you haven't got multiple versions of tabview nuget package installed on different platforms. e.g Xamarin.Android project could have a different nuget package version installed. 
Another thing to note is that the minimum xamarin.forms version required has been set to a higher version : 3.1.0.583944 to support overflowing tab headers and scrollbar visibility.

**Comment by suihanhbr** [comment]
I got the same issue. And I backup to old version 1.0.4, I get the error `Binding: 'HeaderSelectionUnderlineWidthProperty' property not found on 'Xam.Plugin.TabView.TabItem', target property: 'Xamarin.Forms.BoxView.HorizontalOptions'`

**Comment by chaosifier** [comment]
There was indeed an issue with the nuget package. I've updated a new version of the package which is 1.0.6 and unlisted the faulty package. Thanks for the responses!

**Comment by hhuseyinpay** [comment]
I think there is a problem with nuget because I cannot see the 1.0.6

**Comment by agharium** [comment]
> I think there is a problem with nuget because I cannot see the 1.0.6

Me neither..

**Comment by agharium** [comment]
Any updates on this? Only version 1.0.5 shows up here (which is not working alright).

![image](https://user-images.githubusercontent.com/28984633/72011831-678c6400-3239-11ea-9b17-2f455a193355.png)
