### ISSUE TITLE
Binding property name problem

### ISSUE THREAD

**Issue by tmijieux** [chaosifier/TabView#34]
You probably did not meant to have "Property" at the end of the nameof() operator here:
(also there is a warning at runtime that the property name does not exist)

https://github.com/chaosifier/TabView/blob/9a41af2a924ca25b4e94f01887b51ec48d1660ae/Xam.Plugin.TabView/Xam.Plugin.TabView.cs#L262

**Comment by chaosifier** [comment]
Silly mistake. I've updated the source, will update package in the next version. Thanks.
