### ISSUE TITLE
It's not possible to change tab header text dynamically 

### ISSUE THREAD

**Issue by Sztub** [chaosifier/TabView#35]
Replication steps:
1. Changing tab header text  in code.
` TabView.ItemSource[2].HeaderText = "New Text that will be splited into multiple lines";`
2. Switch between tabs.
3.App is crashing 

What i've also noticed, is that you cannot set binding into tab header text, when using prism.

**Comment by chaosifier** [comment]
With new TemplatedItemSource and ItemTemplate bindable properties, you could achieve what you're trying to do. Please look at the sample project for reference.
