### ISSUE TITLE
Tab line delay

### ISSUE THREAD

**Issue by MrPrometheus** [chaosifier/TabView#39]
Hello, I have the same problem as # 3. 
I have a delay at the tab line. When I swipe, the line moves only after 1-2 seconds. Problem # 3 existed 2 years ago. How can I solve this problem now?
![1](https://user-images.githubusercontent.com/46008130/79856522-23326780-83d5-11ea-9e9c-f936f337724d.jpg)
![image](https://user-images.githubusercontent.com/46008130/79856620-3cd3af00-83d5-11ea-8053-0306c5237c89.png)

**Comment by chaosifier** [comment]
The new update should fix the issue.
