### ISSUE TITLE
HeaderSelectionUnderlineWidth

### ISSUE THREAD

**Issue by zaoky** [chaosifier/TabView#4]
Hi, First thanks for this awesome control.

Now I want to have the HeaderSelectionUnderlineWidth that covers the whole tap section, I set as 100 but it doesn't change 

this is what I want to achieve [Image](https://drive.google.com/open?id=1A11ztZvsx8DEHDfBs3XZd_7yOjPnc2oY)

is it possible ?

**Comment by zaoky** [comment]
thanks for your answer. I am new on this, I have a quick question, can I use your control in XAML? I imported but it doesn't appear when I open the tag or it is an intelligence issue?

**Comment by chaosifier** [comment]
That'd be hard to do with the current version of the control. I'll be adding the feature in the next version of the control.

**Comment by zaoky** [comment]
Thanks for your help, now it is working as I wanted :D

**Comment by vishalpachori25** [comment]
Hi,
TabItem.HeaderSelectionUnderlineWidth is not working when there are only two tabs and if you want to set the width to less than the length of the text. Something like this:-
![image](https://user-images.githubusercontent.com/13977139/49016046-e1cf6580-f1aa-11e8-9af7-749bed185365.png)
