### ISSUE TITLE
hide header & selection

### ISSUE THREAD

**Issue by tuke307** [chaosifier/TabView#50]
Is it possible to hide the complete header and selection? 

![Screenshot 2020-12-15 195847](https://user-images.githubusercontent.com/58882912/102259927-03c1ef00-3f10-11eb-80f4-7fc45e2fc492.png)

For now I do this;
```xaml
HeaderBackgroundColor="Transparent"  
HeaderSelectionUnderlineColor="Transparent"
```
But that's not the perfect solution because it gaves me blank non usable area.

**Comment by jakub-sobczuk** [comment]
I am trying to achieve same thing :)

**Comment by tuke307** [comment]
I switched to sharpnado's tabhostview. its fully customizable and you can hide the header

**Comment by chaosifier** [comment]
In the latest version you can design a custom header yourself. Here's an example : 

 <tabview:TabViewControl.TabHeaderItemTemplate>
                                    <DataTemplate>
                                        <StackLayout Padding="10,0">
                                            <Label
                                                Margin="0,10,0,5"
                                                FontSize="16"
                                                HorizontalTextAlignment="Center"
                                                Text="{Binding HeaderText}" />
                                            <BoxView
                                                BackgroundColor="{StaticResource PrimaryBlue}"
                                                HeightRequest="3"
                                                IsVisible="{Binding IsCurrent}" />
                                        </StackLayout>
                                    </DataTemplate>
                                </tabview:TabViewControl.TabHeaderItemTemplate>
